# -*- coding: utf-8 -*-
## This should maybe have some kind of exception in here just in case someone has already labeled
## the fragments. Right now it just assumes they're unlabeled and adds a property to each for the Name.
## If they're already labeled, or if one of them is, this'll probably fuck that up.
##
## (for example, someone might label the original molecules prior to running Blends, which would cause
## an issue here. could be helpful, not sure if it's worth it



# getting the base/screen names, prob would be passed to this function in BARStool prep tab
base = raw_input('yo what\'s the base molecule name fam\n')
screen = raw_input('\nk coo, now u know i want dat screen molecule name\n')
print('\ndope, i feel u, ight give ya boy a sec here')

# building the input and output filename
bb = base+' '+base+'.xtd'
bs = base+' '+screen+'.xtd'
ss = screen+' '+screen+'.xtd'

# increments over each pair for MAXIMUM EFFICIENCY 💯💦👌
for pair in [bb,bs,ss]:
    text = open(pair,'r')
    lines = text.readlines()
    contents=''
    for item in lines:
        contents += item

# theez ma split chars fam, first for separating frag1 from frag2 and second for finding each atom
    sp1 = '</Molecule>'
    sp2 = ' UserID='
    molecules = contents.split(sp1)
    frag1 = molecules[0].rsplit(sp2)
    frag2 = molecules[1].rsplit(sp2)

# each one has a bit of xxxtra txxxt at the start that i dont use in the for loop
    m1 = frag1[0]
    m2 = frag2[0]

# just gonna insert the Name property into each A T O M B O Y E
    for i in range(1,len(frag1)):
        frag1[i] = ' Name="Frag_1"' + sp2 + frag1[i]
        m1 += frag1[i]
    for i in range(1,len(frag2)):
        frag2[i] = ' Name="Frag_2"' + sp2 + frag2[i]
        m2 += frag2[i]
    
# building the new file
    newContents = m1 + sp1 + m2 + sp1 + molecules[2]
    labeled = open(pair,'w')
    labeled.write(newContents)
    labeled.close()
print('\night u good homie, peace')
text.close()

##                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
##                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
##                                                                           `                                    `        `                `                                                     `                           `                                            ``             `             `                                                                             `                 `                                           ` `--/+++++/-.``                                                  
##                                                                       `-::::-`         `.:::::.          `-:::-.   .-:::-`          .::::-`          `.-:/sssssso/:-.`                  .::::-`        ``.:::::.`         `-:::-`        `.-:+ssoosso+:-.``        `-::::-`       `   .::::-`     .::::-` `           .:::::::::::::..``                   .:::::.    `     .-::::-`       ` `-::::.`  `-::::.`     .-:::::-.          .:::-.`   `-smmNMMNNNNmds:.                                                 
##                                                                       .hNNNNm:`        :hNNNNNs`        `+mNNNm/` `oNNNNm+`        `oNNNNm/       `.:ymNNMMMMMMMMNNNdy/.`              `sNNNNm+`       `/hNNNNNy.        .+NNNNd:      ./ymNNMMMMMMMMNNNms:`       .yNNNNh-          `yNNNNm-    `+mNNNm+`           `yNNMNNNNNNNNNNmmds:.`               `/mNNNNy`        .yNNNNNd/        `:hNNNmo.  :dNNNNh.    `smNNNNNNh:``      `sNNNms`   `+NNmmdddmNMMMMNh:                                                
##                                                                       `oNMMMNs.       .oNMMMMMd:        -hMMMNy-  `sNMMMN+`        `sNMMMN/     ``/hmNMMMMNddddmNMMMMMNy:`              +NMMMNy.       .yNMMMMMm/        :dNMMNs`    ./hNMNNMNmddddmMMMMMNmy:``    .hMMMMd:          `yMMMMN-    `oNMMMN+`           .yMMMMNmdddddNMMMMMmdo-` `            -dMMMMN-       `+NMMMMMNs`       .sNMNMh:`  :mMMMMh.    `hMMMMMMMNd+`      `yMMMNy`   `-o/:-...-:sNMMMMh-                                               
##                                                                        :dMMMMd/`     `/dMMMMMMNs.`     `omMMMd:`  `sNMMMN+`        `sNMMMN/    `.omMMMMNho:.``.-/sdNMMNNm+`             .dMMMMm:`      :mMMMMMMMs`      `oNMMMm:    .yNMMMNmy+-.```-+sdNMMNNh:`    .hMMMMd:          `yMMMMN-    `oNMMMN+`           .yMMMMm/.```.:+sdNMMMNd+`             `oMMMMMo`      .hMMMMMMMd-      `:mMNMNo`   :mMMMMh.    `hMMMMNNMMMd/`     `yMMMNy`     `        .yMMMMm+`                                              
##                                                                        `/mMMMNh`     .yNNMMMMMMm+`     -mMMMMo`   `sNMMMN+`        `sNMMMN/ `  `sNMMMNh/.        `.oNMMMMm:             `oNMMMNs.      sMMMMMMMMm:`  `  -hMMMMy.   `oNMMMMh:`         :yNMMMNd-`   .hMMMMd:          `yMMMMN-    `oNMMMN+`           .yMMMMm:` `    `.+mNMMMN+              -mMMMMh-`     /mMMMMMMMNo`     `oMMMMd:    :mMMMMh.    `hMMMMyhNMMMd/`    `yMMMNy`              `oNMMNNo`                                              
##                                                                         .yMMMMN:`    :dMMMmmMMMNy.     +NMMMm:    `sNMMMN+`        `sNMMMN/    -mMMMMm:`           `hMMMMNo`            `-hNNMNd/`    .dMMNddNMMMy-    `/mMMMm/    :dMMMMN:`           -yMMMMNo`   .hMMMMd:          `yMMMMN-    `oNMMMN+`           .yMMMMm:         `+mMMMMd.            ``sNMMMNo.    `sNMMmdNMMMd/ `   .hMMMNs.    :dMMMMd.    `hMMMMs:sNNMNdo`   `yMMMNy`            ` .yMMMMm/`                                              
##                                                                          :NMMMMs`  ``oNMMNsoNMMMm/`   .hNMMMy`    `sNMMMNs//:///////hNMMMN/    /MMMMMy.             oNMMMMy.             `/mMMMMy.   `+NMMN//NMMMN+`   .yNMMNy.   `+NMMMMh`            `+MMMMMy.   .hMMMMd:          `yMMMMN-    `oNMMMN+`           .yMMMMm:          .hMMMMN:              .yMMMMm:`  `-dMMNs:hMMMMh`    /NMNMd:    `:dMMMMd.    `hMMMMy`-hNMMMm/`  `yMMMNy`        `...-:yNMMMNy.                                               
##                                                                          .hMMMMd-   -hMMMy--dMMMMs.  `:mMMMm/     `sNMMMMMNMNNMNNMNNMMMMMN/   `oMMMMMs`             /NMMMMh-              .yNMMMm:  `:hMMMh..hMMMMh.  `:dMMMh:`  `.sNMMMMs              :MMMMNh.   .hMMMMd:          `yMMMMN-    `oNMMMN+`           .yMMMMm:          `yNMMNM+              `+NMMMNo`  .sNMMm/`oMMMMN:   .yMMMN+`     :mMMMMd.    `hMMMMs` -dMMMMm/. `yMMMNy`       `-dmmmNMNMNms.`                                               
##                                                                          `+NMMMN+` `+NMMN/``oNMMMd-` .sNMMmo.     `sNMMMMMNMNNMNNMNNMMMMMN/   `oMMMMMo`             /NMMMNh-               /mMMMMs  .sNMMNo``oNMMMm/` .yNMMNo`    -sNMMMMs             `:MMMMMh.`  .hMMMMd:          `yMMMMN-    `oNMMMN+`           .yMMMMd:          .yNMMMN+``             -hMMMNd-``/mMMNy. -mMMMMs` `+NMMMh`      :mMMMMd.    `hMMMMs`  -yNMMMmo.`sMMMNy`       `/MMMMMdys/-`                                                 
##                                                                           -hNMMNh-`:mMMMd. `-yMMMNs.`:dMMMh-      `sNMMMNy++///////+hMMMMN/   `+MMMMMy`             +NMMMNy.               .hNMMMd. :dMMMd:` -hMMMNs. /mMMMd-    `.sNMMMNy              /MMMMMy`  `.hMMMMd:          `yMMMMN-    `oNMMMm+`           .yMMMMd:         `.hMMMNN:               `oNMMMm/`.yMMMN+` `sNMMMd- -hMMMN+       :dMMMMd.    `hMMMMy`   .hNMMMm+.sMMMNs`        :MMMMN-`                                                     
##                                                                           `:dMMMNo.sMMMNo    /NMMMN/.yNMMN+`      `sNMMMN+` `      `sNMMMN/    :NMMMMd.          ` `yMMMMNo`               `/NMMMN/`oNMMNs`  `+mNMMd:`yMMMMs`     `/NMMMMd.           `.sMMMMMo` ` .hMMMMm:      `   `yMMMMm-    `oNMMMN+`           .yMMMMd:         `+NNMMMd.  `             -dNMMMy`:mMMMd-   :dMMMN+`+NMMMd.       :dMMMMd.    `hMMMMy`    :hNMMMd+sMMMNs`        :NMMMN.                                                      
##                                                                            .sNMMMd+dMMMm-    `hMMMMhomMMNd- `     `sNMMMN+`        `sNMMMN/    .dMMMMNo.`       ``.+NMMMMd-                 .sNMMMy/hMMNd/`   .yNMMNy/mMMMm:       -hMMMMMo.  `       -sNMMMNd-    .yMMMMNo`        `:mMMMMd`    `oNMMMN+`           .yMMMMd:       `-omMMMMNo                ``/mMMMm/oNMMNo`   `/mMMMd+yNMMNo`       :dMMMMd.    `hMMMMy`    `.sNNMNNmMMMNs`      ` .+ooo/`                                                      
##                                                                             /mMMNNdNMMNs.    `oNMMMNdMMMNs` `     `sNMMMN+`        `sNMMMN/    `+mNMMMNh/-`` ` `./hNMMMMm/`                  :dMMNNdmMMN+`    `/mMMMNhMMMms`       `+NMMNMms/.` `  `-/hNMMMNh:`    `+mMMMMmo-``   `-+dNMMMNo`    `oNMMMNo-........` `.yMMMMm/.....:/sdNMMMMms.                  `sMMMNdmMMNh.     -hMMMNdmMMNh-        :dMMMMd.    `hMMMMy`      .yNMMMMMMMNy`        `:///:`                                                      
##                                                                             .yMMMMNMMNh:`     -dMMMMMMMMd-        `sNMMMN+`        `sNMMMN/     `:hMNMMNNNdhhhhmNNMMMNNy-                   ``sMMMMMMMMd-      `hMMMMMMMMy.        ``omNMMMMNmdhhhhdNNMMNMNy-       .smMNMNNNdhhhhmNNMMMMd/``    `oNMMMMNNNNNNNNNNs. .yNMMMMNNNNNNNMMMMMNNh:`                    :NMMMMMMMN+      `oNMMMMMMMm:`        :dMMMMd.    `hMMMMy`       .hNMMMMMMNy`       `+NNMMNo`                                                     
##                                                                             `/mMMMMMMm+``     `omMMMMMMm/`        `sNMMMN+`        `sNMMMN/    ```.+dNMNNMMMMMMMMMMMms/.` ``                  :dMMMMMMMo`       +NMMMMMMm/`          `-omNMMMMMMMMMMMMNNmo:`        `.:sNMMMMMMMMNMMNMMds-``     `oNMMMMMMMMMMMMMMh-`.yNMMMMMMMMMMMMMNmho:.`                     `hMMMMMMMh.       :dMNMMMMNs.         :dMMMMd.    `hMMMMy`        .oNMMMMMms`        sMMMMMy`                                                     
##                                                                              `:syyyss+.        ./sysyss/           :ssyss-          :sysyo.         `:osydmmmmmmdyo+-                         `/syyyyso.        .+syysys+`              .:oyhmmmmmmmhyo/.              `-+sydmmmmmmhys/``        `-+syyyyyyyyyyyys/```/syyssyyyssyso/:-`                          -oysyyys:`       `:oyysyyo-          .oyyyy+`    `/ssys/`         `/sysys+.        `:dmmmd/                                                      
##                                                                                                                                                                `                                                                          `  `    ``                            `                                                                                                                                                                      `                                                           
##                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
##                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
##                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
##                           `                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
##                           `:o+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oo+oo+:`     
##                           .hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd-     
##                           `-///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////hNNNy///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////:-`     
##                              `                                                                                                                                                                                                                                            `sNMN+                                                                                                                                                                                                                             `     
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                         ``                `sNMN+                                                                                                                                                                                                                                   
##                                                                           `                                          `                          `                                     `                                                   `.`          `oh:               `sNMN+                                                              `` `...``         `.`       `.`         `......` `         `.`           `..      `.`        `.....`            `  `....`           ..`     `..`                     
##                                                  `                  `                       `..`                    `           ` `           ` `                   `                                `               `                `  `hd/` ``.```` `sm/               `sNMN+                                                             ``-+hhhhhs+`       -dy`      +m/        `+mdhhhdho.``       +mo`          -hd:`   .sd:       -hmhhhhds-```       `:oyhhhhds/``      `od+`   `+do``                    
##          ``````            ``````    ``````     ````````  ``````   ```````.     .``    `` ``.dm-``    ````.` `  `` ````       ``` ````     ```````   ````.`    ` ````````  ``````` ` ``````    ``` ````   ````         ```    ```  ` ```  :/.``.+No..```sN/``````         `sNMN+                      `````     ````````       ```` `         +md+`  `:s.       :mh`      oN+`        oN+  `.yNy`       `oNs`          `-dd:` .ym/`       -dm ` `:Nd- `      .smy:` ` :sNy.       .sN+```/Ns``                     
##         /shhhhy/`         :oyhhy+. `-+hhhhyo`` `oh+oyhhy::ohhhs.   /h/oyhyd+.  .hs.   .yd``ohmNhhy. `-oyhhhs:   /d+shho       :h/+yhhd+.`  yy+yhy:``:shhhhy/`  `/yhhhddhs` :hoohho``+yhhhhs-`  :h++yhhh/-+yhhy:`     ``/do`  `odo`   +h/` oh:`.hdNmhh+  sNooyhhy:`        `sNMN+                   `:ohhhhy/`  `sy+oyhhs- ` `:ohhhho-`       -Nd:``             :mh`      oN+`       `oN+`  `oNy        `oNs            `-hd:`ym+`        -dm`  `-Nh-       `+Ns.      .yNo        `oN+`+my`  `                    
##        `::....ym+`  `   `/my-``-s:`/my:.../mh-``sNh/.`/mNh/`.+mh` `+Nd+.`.sNs.`-Nh-  `.hN```.dm-````/dy-..-yN/``oNd+.``      `/mm+-`.+Nh.` hNh:.```smo-.`.sms. /Ns.`.oNo. `/mmo-````/-...:dd- `/mm+.`.hNd+.`:hm: `     .yN: `/mNm:  -Ny.  ym/``.+No..` `sNh/.`:dd-        `sNMN+                  `+my-``.+my.``hNy:.`/dd. `+mo...:hd:       oMy`               :my`   `  oN+`        oNhssshdo.        `oNs             `-hdym+`         -dNssssmy/`     ` .sM/`      `oNh        ``ymydy``                       
##       ``-/yyyydN+`      .ym:  ``  .ym: ` ` om+``sm/   .sm:   .hN`` oN+````.hd-`-Nh-  `.hN````dd.   .hNhyyyydNs``oN+````      `/ms   ` ym/  hd:`` `:dd`   `.hd-`:dh+//ym+```+ms `` ``:oyyyhmm- `+ms ` `/Ns````oN/`       :dd`.yd/Nh.`hm:   ym/  `+N+``` `ym/ ` .oN/        `sNMN+                  -hd-`` ` ym/ `hd:`` .yN- -hNhyyyydm+       +My``              :mh`      oN+         oNs::odd:``       `oNs            ` `:dM/``         -dm::::/dmo`    ` .sN+`      `oNs          .yMs.`                        
##        -dd/...sm+`      `ym:`  ```.ym:  ```sm/``sm/ ` .sm:   .hN`` oN+`  `-dd-`-mh-  `.hN`` `dd.   .hm/.-...-. `om+`          /ms``  `hd/` hd:`  `:dd`   `-dd- +dsooo+.`` `/ms`  ` +my-..:hm- `+ms   `/Ns`` `oN/        `oNs+m+`sNooNs`   ym/` `/No`   `sm/`  `oN/`       `sNMN+                  .hd-    `hm: `hd: ` .sN: -hm:......`       .mm/`     `        .dm-     `yN/`        oN+`  -hd-        `oNs            ```.hM-           -hm`    -md-      `/Nh.      -hm:        ```oMo``                        
##        :md/--odN+`      `:dd+--+h/`:dd+--:sms```sm/   .sm:  `.hN`` oNms:-:hm+` .sNs:-+hNN````hmo--``/dd/:--/s.` oN+`          /mNy:-:yNo```hd:    `oNy/--/hm/` +mhsssso:` `/ms     +Ny:-:ymm- `/ms    /Ns   `oN/`        `hNmy. .hNNm``   ym/` `/mh/-. `sm/   `oN/`       `sNMN+                  `+md/--/ymo` `hd:`  `sN-``/mh/--:/o`       `-hmy:--:od.       `:md+:--/hmo`         oN+`   /md.        oNy-----.       ` .hM-           -dm:---:ymo`       `+mdo----sdd/`          `oMo`                         
##       ` -oyyy//s:         .+syyo:`  ./syyy+-`` `+s-   `/s-```.oy`  oNo/syyo.````./sys+-+y````.oyys.``./syyys:`` /s:           /my:syyo-`  `oo-    ` -+yyyy:.```odo:--:sms``:s+     `:syys:+s.``:s/   `-y/   `:y-`        `-ys:` `:yy: `   +s:` ``:syy/ `+s-   `/y:        `sNMN+                    ./yyyy/.``  +s-`  `+y.`` -/yyyyo-`        ``-+yyys/.``        `/syyys/.`          :s:`   `/y/`       :yyyyyys:`        `oy.           .oyyyyyy/.```        .-syyyyo-` `          `/y:`                         
##       `` ```` ` `            ` ` ` ```     `                       oN+`````` `  `` `         `` ``````   ``` `  `             /ms `  ``    `       `````` ``  .Nd:...-ymo``` `        ``    `              `                      `  `       `     ``        `            `sNMN+                     ````  `            ````   `` ` `          `      ```             `      `           `   `` `         `      `                            `    ` ``       ```   `    `                                         
##                                                                    /h:`                                                       :y+`                       `     -ohhhhho-`                                                                                                 `sNMN+                                               `                                                                                                                 `                                                                 
##                                                                     ``                                                         ``                              ` `   ``                                                                                                   `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                           `                                                                   `         `                                                               `                                   `                                             `sNMN+                                    `  `          ` `                                                `    `                                                 `                                                                      
##                               `  :o:   /o-`       `                                                     `/sss``     -o+ `                                                           `.+ss/`                                   .o+`                                        `sNMN+                                   `              `/o-                                               `:sss.         `                                   `:s-                                                                       
##                            /y+` `oN+   ym/` .sy-                                                      ` smo::`      :mh  `/h+                                                       -hd/:-`                                   .md`                                        `sNMN+                                   ``sy:          `sm/                                              `+ms::`        `oy/                                 `oN/                                                                       
##        `  ````  ` `        :o/  `oNo   ym/  .+o.         `            `          ``     `        `    ``Nh.         :mh   :o/     `` `       `      ```     `                   `  `/No`         `      `            `   ```` .md```  `    `                              `sNMN+                `       ``      `  ` +o-` `/m+`   `sm/`             `  `` ` ` `    `                `dm-   `` ` `  `/o:    `       ``   `       ``     ``oN/`                                                                      
##        `/s:/sss+..:sys/`   :s/```oNo   ym/` `+o. ``.:ossso:`  `/o-/oss+.` ``:osyo-`       `.:ossso:```+yNmys/`      :mh   :s/` `/s:/oss+.    .:osss/.   ./yss+.         ./ssys/.` .shNdys-        :+sss/.`  -/ssss/. ```./sss/:md`   -+syyo-`                             `sNMN+                ` :s/````/s/  ` :s:``/s- .shMdys/``sm+/oss+.         -s/-osss-` ` `-+ssys/``      `/yNNys+`.o+-oso-`:s:`  `-+yss+-```.o/-oyss:`````:osss:oM/`                                                                      
##        `sNdo:-omdho::smy   /Ns` `oNo   ym/` .hd: `-hdo::/sms.``yNdo::omh-``+mo:://` `     -hdo:::sms.`-/Nd/:.       :mh   /ms```sNdo::+mh-  -hh/::+hd- .ym:::o-       `+dy+::/hm+``:oNs::`      `oms/::ss.`ody/::+hd/``-hd+::ohNd```ods:::sdo``                           `sNMN+                  -hd-``-dNd-  .dh-` ym/``:sNs::. `sNdo::omh-       `/mms/:/dm/  `yds/::odd-`      .:mm/:-`.dmh+:-``+No  `sdo:::yd+` :mmh/:/yN+```oms/::ymM/`                                                                      
##        `yN+   .yN/`  .hN`  /ms` `oNo   ym/  .hd-``ym/`` ``sm/ `sN/` ``sN/``+dyo-.``  `   `sm/``  `sm/ ``Nh.         :mh   /ms```yN+   .sN/ .yNso+oohNs`.smo/-.        -dm`  ` -dh- `+N+`        :my` `  ``:mh` ` `:mh..yN/`   -md` :mdoooosmd:`                           `sNMN+                  `/my``smoNy.`sm/   ym/` `+No` ` `sN+` ``sN/        /my`  `:Ns` /Ns``  `/my`       `dd.   -dd-    `oN+ `+Nho+oosmd. :mh.`  -mh` :mh`````sM/                                                                       
##        `sN/   .sm:   .hN`  /ms` `oNo   ym/  .hm: .ym:    `sN+ `sm/   `oM/` `-/+hdo. `    .ym:   ` sm+ `.Nh.         :mh   /ms```sN/   `oN/`.hmo//////-  `-/odh+       :dd ``` .hd- `+N+`        /ms`` `   /my`  ``:dh..ym: ` `.md` /md+/////:.                            `sNMN+                   `sN//mo`ym//my`   ym/` `+N+``  `sm/   `oM/`       /ms    -My` +No ``  /mh`       `dd.   -dh-    `om+ `oNh//////:``:my.   .md` /mh``` `oM/                                                                       
##        `sN/   .sm:   .hN`  /ms` `oNo   ym/  .hd:``+my:..-+mh.  ym/   `oM/``:-..:dd:``    `+my:...+mh.  .Nh.         :mh   /ms` `sN/   `oM/``+my:...-/``.:...+mh       .yNo..`.omo` `+N+`        .hm+...+o..hm+...-ym+``+my-..:sNd``.hm/.`..:-`                            `sNMN+                    -dmdd- -dmmm-`   ym/`  /Ny-.` `sN/   `oM/`       /ms    -My` -md/...:hm/        `dd.   -dh-    `om+  -mh/..`.:-` :my`   .md``.hm+...+dN/                                                                       
##        `oh:   `oh:   .sd`  :ho`  /d/   oh:  .sh- ``:shyyhs+.  `oh:   `+d/``oyyyyy:```    ``:shyyhs+.   `ds`         :hs   :ho` `oh:   `+d:` `:shyyyyo``-syyyhs-        ./yyyyho/`` `/d/`         .ohhyys/` .oyyyyyo:`  `/yhyys/hy`  `oyhyyys:`                            `sNMN+                    `/dd+` `/dd+`    oh:   .ohyy/``oh:   `+d:        /ho    .ds`  -oyyyyyo-`        `yh.   .yy.     +h/   -oyhyyys-  -hs`   .hy`  .ohyyy+od:                                                                       
##         ``     ``     ``    ``   ```   ``    ``      `````     ``     ``    `````            ````       ``           ``    ``   ``     ``      `````    `````            `````       ``            ````      `````       ````  ``     ``````                              `sNMN+                      ```    ``      ``      ````  ``     ``          ``     ``     `````            ``     ``      ```     `````     ``     ``     ````  `                                                                        
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##               :------------:--:--------------::-:::-:::::------------::::-:::-:-----------:-::-:-:-:-::-::---:::::-:--:::::::::--:::::::::::::::::::::::::::::::::::::::::::::::::---:::::::::::::::::::::::::::-.-.----:::-----::-------:::::---..`                      `sNMN+                                                                                                                                                                                                                                   
##               ddhysyyyhhhhddddhs+oshdyo+++oshddddddddddmddddddddddddmmddmdmmhsohdddddmmmmdmdmhyhdyyhdhyhmmdsymhhddmmmmmdddmmmmmmmmmmmmmdmmmmmmmmmmmNNmmNNmmmmmmNNmmmmmmmmNNNNNNNNNmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNdyhhdddmNNNdhhyhNNmhhhhdmmNNNmhyyyy-`                     `sNMN+                                                                                                                                                                                                                                   
##               dhs++/+++oosyhddy++oyhyo///::/+syhdmhs+oyddhysshdmhsoossossooss/:ohysydysyhyshh/-+h+-oho-/dh+/yh::/ymmmmh://hmmmmmmmmmh/s+hmmmmms+oommmmmmmNmmmNmmmNd++dmNNmNNNNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNNNNNNmmmmNNNmmmmmmmNNNNmmddm-`                     `sNMN+                                                                                                                               `                                                                                                   
##              `hs/:://+++++oyddhyyyhddhyyo:-/:+shdh+---ohho::/ohdo:::-..----/+:/so:-:::oo:--:/:-/ho-smy:+d+:sddhhhdmmmmdyhhdmmmmmmmmmdyhymmmmmmyyyymmmmNmmmmmmhsosmmh-ommdshmNNNNNmmhyhmmmNNNNmmmmmNNNNNNmmddmmNNNNNmmmmmmmmmmmmmmmmmmdhyyydmmmmmmNN-`                     `sNMN+                                                                                                               `.-::////+++++++/``                                                                                                 
##              `y++/://++/::+syddddddddddh+:::-:oyds:--:ohhyooshdd+/o+:------//-::-..--:o+--:----:o/-sho-od::hmdmmmmddmmmmmmmddmmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmdoo/:hmm-+dNs+ymNmmNNdy/::smNNNNhsooosdNNNNmhs++ohmNNmmdyyyyhhhhyhhhhyyhhdhysyhddhhdddm-`                     `sNMN+                                                                                                            `-+yhmNNMMMMMMMMMMMh:`                                                                                                 
##               yss++++oo+//syhddddddddddy++o/:+shdhsooyhdddddmmmmyhddyoo+:/oss+osoooysosys+osyhyso++oo//+h+-ommmmmms/ymmmmmms-smmmmmmmmmmmmmmmmmmmmmy/ymmmmmNs-o-/dNy-smmysdmmNmmmy:---omNNmmyo///ohmNNmho:--:smmdmdysssyyssoossssssyyhyyyyyhhysssyy-                      `sNMN+                                                                                                         ``+ymNMMMMMMMMMMMMMMMMh-`                                                                                                 
##               hysssssyhyssyyhhhddddmdddhsssoosyyhddddmmddmdmmmddddmmmddhhhdmmddmmddmmmmmmmmmdmdddddmmmdmmhoodmmmmhoydmmmmmy/odmmmmmmmmmmmmmmmmmmmmdo:hmmNmNmdysyhmy:odmd:-ymmNmNmy///+ymNNNNmmddddmNNNms/:-:/syooyhyyyhdhssoossssosyyyyyysyysooooos-                      `sNMN+                                                                                                        `:yMNMMMMMMMMMMMMMMMMMMh-`                                                                                                 
##               yoooooyyhyssso+ooosyhdddho/::::/::+shdddmdddddddddhhdddmmdddmmmmmmmmmdmdmmdmmmmmmmmdmddddmmmmdmmdmmmmdmmmdmmmmmmmmmmmmmmmmmmmmmmmmmmdhdNmmmmmNmNmmmdshmmho+ymNNmmNNNmmmmmNNNmNNNNNNNNNNNNdysoshdhysyddhhdmdyyyyyssssyyhyyssssysooosss-`                     `sNMN+                                                                                                      `.omNMMMMMMMMMMMMMMMMMMMMh-`                                                                                                 
##              `so+++osyyyoo+:::/+osyddmho+++/+o:-://oydmds//+++++::+ossssoossosydmmmhsydmmmmdhhdddddho+ymhoyddydmmd//hyoosdmmmmhsyymhodmmdmmmmmmmmmhymmmNmmNNmmdmmNmmdmNNmNNmmmmNNNmNNNNmNNNNNmmNNNNNNNNNNNmmNNNmmNNmmmNNNmddddhyyyhddddhyhhhhyyyhhh.`                     `sNMN+                                                                                                      .ymMMMMMMMMMMNMMMMMMMMMMMh-`                                                                                                 
##              `ssooosyyys++::::///:+shdddhhdhhy/-://oydms/:/:--:::://+//:///::/ohmmh+-:odmdhsosyoo+shsoyho+yh+/+yh:/hds+/smmmmmy/+/dd+/mmmdmmmmmmmmh+yNmNNmmdo/:smmy/odyooohmhhhhmmNNmmNNmmmmmddmmNNNNNNNNNNNNNNNNNNNNmNNNmmmmmmdddmmmmmmmmmmmmmmmmm-                      `sNMN+                                                                                                     .+NMMMMMMMMMMMMNNdhso++++/:``                                                                                                 
##               yhyyyhhhyso+++//+/--/syddddddmds/:/:-/sddysss+///+////:://oso+/+ohmh+-.-+oohhs+osososyoohdsoyds+hdo-smmmmmmmmmmmmmmmmms-mmy+hmmmmmmmdoymmmmmms/:smms:smms+++hyoo+ohdmmddddddmmhooymmmdmmmmmNNmNNmmNmdyooyhhysyhmNNNNNNNNNNNNmdhdmNNNm.                      `sNMN+                                                                                                     /dMMMMMMMMMMMmy/````                                                                                                          
##              `hhhhddddhhyyyys+++++shddddddddhsoso/+sydmdhddhyyhyyyysssyhhhhyyhhdmds++osooyhssso+osys++syo+shs+shs-smmmmmmmmmmmmmmmmm+/mmhhmmmmmmmmhoydmmmmmms:/yd:/mNmmmmmhs+++osshyssooooyhy+ohdhssssyhhdhhhhyyydyo//oshs+/odmNNNNNNmddmmdysosdmdh.                      `sNMN+                                                                                                    `+MMMMMMMMMMNh:.                                                                                                               
##              `sssyhyhhhhyyyyysssyyhhdhhoooosyhddhssyhdmdddddddddddmddmmmdmmmddmmmmmdddmddmddddyyhddddddddhdmddddd/:hmmmmmmmmmmmmmmds/ymdo:ddmmdmmdyodmmmmNdy++/yh:/mmNNNNmyo+/+sooyoosossoshyooyysssooosyyssoooooyhdhhddms///ymNNNNmhsssyhhooo+yhso``                     `sNMN+                                                                                                    -sMMMMMMMMMMy:`                                                                                                                
##              `oooooooooooooooossooooso/:/::/ohddyssyhdddhhhhhhdddddmmmmddmmmmmdmmmmmmmmmmmmmmmdmmmmmmmmmmmmmmmmmmdydmmmmmmmmmmmmmmhsdmmyoymmmmmmdyohmNmmmmmy+ydmmo-smNmmmmdyyyhdyooossshysyyo+ossooooooooooooo+ooydmNNmmmy+//ymddmmyso+shdhooooyhso.                      `sNMN+                                                                                                   `/hMMMMMMMMMMs`                                                                                                                 
##              `soo++++++++++o+++++////:--//::+ydhsoshddyyssssossosshdmds+oydmmdhhhdddmmdhhmdddmmmmmdmmmmdmmmmmmmmdyydmmmmmmmmmmmmmmmmmmmmdmmmmmmmmddmmmmmNmNmmmNmmmssmNNmmNmmmmmmmmddmmdmmdddhyyhhhsoosyyssyyssssshmmNNNmho//+hhyysyys++ohds++++yyo+.`                     `sNMN+                                                                                                   `odMMMMMMMMMMo`                                                                                                                 
##              `yyssssssssssssoooo+++++:-:/::/oydyssyhddyo++o//++osyhddo:.-+hmho::/ydmdy/-/+::/+/:/sy/+ssyhshdmmmh//shdddmmddmdmmmmmmmmmmmmmmmmdmdmmmmmmmdmNmmmNmmmNNmmmmmmmmmmmmmmNmmmNNNNmNmmmmmmmdhyhmmmmmmmddddmmNNNmhyo+ohmhyyyhhysssyyyo++osyoo.                      `sNMN+                                                                                                   `odMMMMMMMMMMo`                                                                                                                 
##              `ddhhhyyyyhyyyyyyyyyyyyyo///:/oyddyssshddysssoo+osyhddmh/-.:ohmds++ohdmy/..--:+o:-/++:--:-/:/hmmmy/.:so:/:s+++oo/++smmmmmhsshhy/shdddhdmds+dNmmmmmNNmmmNms/smhs+odNmyoymdhhdmmmmmmmNmmddmNmmmNNNNNNNNNNNNmdhhhdmNmmmmNNmdhddddhyyyhdys.                      `sNMN+                                                                                                   `smMMMMMMMMMMo`                                                                                                                 
##               hddhs+o+ooo+osyyyyyhhhhhyyssyhhddhyyhddmddhhhyhhhddmmmdyooshdmmddddmmmy+::++shdo+hd+---+/.:hmmmmdo:yd//hy/:ho:-::-/mdmmmo/shds:yym:/+/dy/+dm/++omho++smo:smy///sddo:+hh/::/ydyssyddhssyhdyyhmmmNmNmdhyhdmdhhdmmNNNNNNNNNNNNNNNNNNNmmm-                      `sNMN+                                                                                                   `smMMMMMMMMMMo`                                                                                                                 
##               ssys/::-://////+oosssyyyyyyyyyyhhdddddddddddhhdhhhhdhhmddddmmmmmmmmmmmmdddddmmmddmmhyyso::yhyyyhdysddosdNy/++s:+/:ommmmdyo/sms:hdh:hdymm++mh-ys:d-/o-yh-+mNh+:/yms-/dmmyssshso+ooysoosyhsooydddhddho+:/+yyo++dmmNNNNNNNNNNmNmNNNmdhhd-                      `sNMN+                                                                                                   `ymMMMMMMMMMMo`                                                                                                                 
##               yyyo::-.:/+++/://+oooo+++++oso+oshdhhhhhyyyysss+//+++ohmmmdmmdmmmmhyydmdhhdhdmmmmmmmmmdysyds++++ymmmmdmmmmdddddddhyhhhhdyyydmdooyhommmhs//ys:do+y.::omy.ommmy/::h+-smmNmmmmyo+++oso++syhsooyysoooyyysoosdy+//omNNNmddddddddddhhddhyss.                      `sNMN+                                                                                                   `ymMMMMMMMMMMo`                                                                                                                 
##              `hhho//:-/osys+++++o+++/:///+o++oshhysooo++ooooso++s/:/ydmhyyyyysshs::sh+/os:/hmmmmmmmmmmmmmmmmmdmmmmmmmmmmmmmmmmmmhsssshmmmmmmmmmmmmmmmdddmmdmdd+-+::hd::hms:/+ymo-+dmNmNmmyo+ooyhsosdddsooyysosooymmmmmmd+/:+dmmmmhyyo+yyoooo+syyo++.                      `sNMN+                                                                                                   `ymMMMMMMMMMMo`                                                                                                                 
##              `ddhyso++oyhhhyssssssooo++++oooossyyyooo+//+o+oyhhdh+-/shhs/:://--+o:/s+-+hh:-odmmmmmmmmdhydmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNyooosmmh+smdyhmmmd/:smmmNmmdhyyhddhyhddyo+osssyyssymmNNNmh+:/odhyyhdyo::++/:-.-/+oo++.                      `sNMN+                                                                                                   `ymMMMMMMMMMMo`                                                                                                                 
##               sossyyyyyhdddddhhhhhhyyyyyyyyysssossssssooooosyddms::+++so/-::-..:/-/o::sdm/-oddmmmmmmy/:+ymmmmhssyhmmmmhhmddddddmmddmmmmmmmmmmmmmmmmmmddmmmNmmmmmNmmNmmmmmNmmNmNNdyhmNNNNNmmmmmmmmmmmmdhhhhdddddhdmNNNNh+//+ydyyssdho+//+//-.-::////`                      `sNMN+                                                                                                   `ymMMMMMMMMMMo`                                                                                                                 
##               +++++oosssyyhhhhhhdddhyyhdddddhhysyyhdddhhhhhhddddo+oyyyhhysyo+//+/:/o:-ods-:yy/odmmmd+-ohmmmmmo///smmmm+/h:yo:+yho++ymmmmmhymhhhyhhmdh/smmmmmmmmmmNNNmmmmmmhoymNmNmmNmmNNNNNNNNmNmNmNNNNNNNNNNNNNNNNNmdyyoshmmdhhdmmhhyhhhs+++oos+++.                      `sNMN+                                                                                                   `hNMMMMMMMMMMo`                                                                                                                 
##              `oo+///+++oooooooosyhhysssyyyyyyhyyhhhdddhyyssyyyhdhhddmmmmmddmddddhhhds/+s++sh+-+hmmmmy//odmmmmddhhdmmmd//o:yy//yo-++odmmmm++d+s+/s/ydy:ymh++/yhomhhmhsshmmo:+dmmdmmmmmmmmmmmNNmmNmNNmmmNNNNNNNNNmNmmmmmmddmmmNNNNmNNmmmmmmddhdddhyyy.                      `sNMN+                                                                                                   `hNMMMMMMMMMMo                                                                                                                  
##              `hyso++++++++//++osyhhyoooooo++ooooooossso+/::/::+ymmmmmmmmmmdysydmdhddhdddhdmdyyhmmmmmmmdmmmmmmNmmmmmmmmyooshs++yy++ohmmmmd/os/y/yd/ymh-hd/od:so-mo+s://:hy-+dmdo/:odo+++shssosddyyhdddmmmmmNNNNmmds++shmmNNmNNNNNNNmmNNNNNNNNNNmmmmm-                      `sNMN+                                                                                                   `hNMMMMMMMMMMo                                                                                                                  
##              `ddhyysssssoooooossyyysoo++//::::://///+//++oos:-/sddhsssssosy+-/hs//s+/shs+sdyoymmmmmmmmmmNmmmmmmmmmmmmNmmmmmmmmmmmddhyyyyhhysydsddshs+:sh+++-s+:s:o+./+od+-sNms::-:s-:+++/-://os/:-/++syoohmNNmmh+/-/syhyyhdmddddmmdddmmmmmNNNmmmmmN-                      `sNMN+                                                                                                   `hNMMMMMMMMMM+                                                                                                                  
##              `ddddddhhhhhyyyyyyysssssssoo+/:::::///++/+oyhdh/-/oyyo:--:-.-+/-/o-:oho-/yo-:ys-:hmddmmmmmmdssmNdyydmNmmmmmdmmmmmmmmmmdhyyyhmmmmmmmmmmmmmmmmdo:hdysshdo++sms-+mh/-:-/o:ommd::sdho:-..:/:::/+hmmNmho-.-/++/:/+/+oo++oo+++oyhmmmNmdhhhdd-                      `sNMN+                                                                                                   `hNMMMMMMMMMN+                                                                                                                  
##              `yyhhhhhhhhhhhhhhhhyyyyyyyyyso+++++osyssssyhddo::++/so/::-...:--//-/yms-:yy-:yh:-sh/+dmmmmdo:odd/:ohmmmmmy:+dmmmmmmmmmmmmmmmmmmmmmmmmNmmNNmmmdhmmNmNmmmNmmNm+:smdyyyhhyhmmdsohmmo:---+y/--odmmmmmms/:/so/::++:::-/:---.-:/sdmmmdys+oss.                      `sNMN+                                                                                                   .dMMMMMMMMMMd/                                                                                                                  
##              `sooossssssssssyyyyyyso++++oyyyssyyhhdddddddmdsosyhhhhyyys+/++/:++-:sh/-+ho-/hy:-yhoymmmmmmo:sh+-/sdmNmmy-odmysshmmmmmmmddmmmmmmhyyhmmmmmmNmmNmmmmmmmNmNNNNmmhdmNmNmmNNmNmNmmmmmmhyyyyo::+dhhyyhddhysydysosdy+/:-/--....-/odmmmhs+-::/`                      `sNMN+                                                                                                  `:dMMMMMMMMMMy:                                                                                                                  
##              `oo+ooooooooooooo+oo+:::/:/+osssssyhhddhhhhhdhysydmmdmmmmmdddddhdh++oo/+ys:/yy/:od+-/dmmmmh/:oms:smmmmmm+-hms:shdmmmmmdsosmmmmmmdds+dmmmmmyo+ydmmmNmhsmmmmmNmNNNmmNmmNNmmmNmmmmmNmNNmyoosdho/:::/ohdddmdhhdmdho+++/o+////+sddmmhs/-://`                      `sNMN+                                                                                                  .smMMMMMMMMMN+.                                                                                                                  
##              `syssssssssooo+++////--:+oo++oo+++++ooossooos+::+ydmmmmdmmmmmmmmdhhddddddhyhmhoydy//sdmmmmhsosdhshmmmmmm+-dmo:yhmmmmmdo/yNmmmmmmmyosmmmmmms/:odNmmmmo-shdmNNNNNNmNNmNNmNmmdhhhmmyshmmmmmmNmdhyssshmNNNmmmmNNmmmddddddhhyso+++ossyso+ss.                      `sNMN+                                                                                                  /mNMMMMMMMMMN-                                                                                                                   
##              `hdhhhhhhyyyysssssso+:-/shhsooo++//://+oo+//ooo+sydmdyyydmmmdhhhy//sdmmmmmmmmmmmmdddmmmmmmmmmmmmmmmmmmmmh:+mdyssdmmmmmmh+hmmmmmdoohmmmmmmmmhhdmmNmmd/-o-+mNNmmNNmNNNNmNNmds++sddo::ymmmmmNmmhysydmmNNNNNmmmmmmNmNNmNNmmdhys+/+syyhhhdm-`                     `sNMN+                                                                                                 -sMMMMMMMMMMmh.                                                                                                                   
##              `ddddmmddddddhhhhhhhyo+oyhdhyssssso++++oo+/+oydddmmds:-/sdmho-:oy/-+hmmmmmmmhsyhhshdmdyydmmmmmmmmmmmmmmmmdhdmmdmmmmmmmmmmmmmmmmdyysydmmmmNmNNmNmmmmh:sd-/dmmNNmyooydNmmNNmds+sdmd/-/dNmmNmmdssohdmmNNNmmmmmmNmmNNmmmmmmNmddhhhhdmmmmmN-                      `sNMN+                                                                                                .yNMMMMMMMMMMh/`                                                                                                                   
##               yssydddyyyhdhsoshdddhhhdddddhhddhhyyyyyysssyhdmmmmds/:/sdmy:-/yd+-+hmdmmmmds/+so/+syy+oddhddmmmmmmdhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmmNNNmNdo//+dmNNNNmdhyhmNmNNmmdooymmd/-/dmmmmmhyssymmmmmNmhsooshhhhyhdhyssydmmmmmmmNmmmNNN-                      `sNMN+                                                                                              `-ymMMMMMMMMMMmo`                                                                                                                    
##               oooyhyo::+shs/////+++osyysssyyyhdddddddddddddmmmmmmdhhhdmmdo:/so-:oo//hmmmmyooyooo+yy+ohs++ydmmmh+-/shhhdmms:ymmmmmmmmmmmmmmmmmmmmmmmmmmNNmmNmmNNmmmmmmmmmmmNNNmNNNNNmNmyo++shdy--ommNmmmhssshmmNNmNh+///o/+///++++::+syhhhddhhyyhhdd.`                     `sNMN+                                                                                            .-sdMNMMMMMMMMMm+.                                                                                                                     
##               ysshhs/--:/o+:-......---------:/oyys+oshdddmmmdhhhmmmmmmddmdddyo/sy/-/ymmmmhoosossoss/ohy++sdddmmo-+hs./-+y/:dmsoosddhhdmmmmmmmmmmdmhohmdddmmNmmNNNmmmmmmNNNNNNNNNNNNNmmmdhhhds::odNmNNmmdyoshmmNNNmyo+/yy+/:-:///+//oooyooys/+++oo+o.`                     `sNMN+                                                                                     ``.-:/ohNMMMMMMMMMMMNm:.                                                                                                                      
##               dhhddho/://o+::-.......``......-:/+/.-:+oyhdhhh+/+ydmmmhsyhmmmdddddyyhdmmmmmddddddhhyosysooyh/:hmo-od+:hhhmo:dy:s:+s/o:oyoo+hhosodmy:sdd:/:ommmmmmhsymmmmddmNNmmmmmmmNmmmNmmmdyoymmmmNNmmdyooydmmNNmhyysmmyo///+oso//ooo+:/o//+//so++.                      `sNMN+                                                                                    .shddmNMMMMMMMMMMMMNh+-                                                                                                                        
##              `hhhhhddhhhhhyso+/+++/-.`..--------:-...--::::+o+-:sdmmhooyhdmdo//osooydmmmmmmmmmmmmmmmmmmmdmmdddmdsoyssdmd+::yo.-/d+-//d-:o:so:hood:smmmhdyhdyyshmdo+hmds+ymmmmmmdyhmmmmhhddmdhhmNmmNmNmmmdyyydmmmmNmmmmmNmhysyhddyssysso++o/oyyyhyys.`                     `sNMN+                                                                                    -dMMMMMMMMMMMMMMMdy/.`                                                                                                                         
##              `yysooyyhdmddhyhhhhhhyo:-:/+oooo+:--:--::-:::-:+/-:sdmdyoshdmmds//+/:-+hmmmdoohmmmmmmmmmmmmmmmmmmmmmmmmmmmmddhh::o-+:/+/ho/osm/smdmh:ymmmmmmmo+yhdmdooddy++ymdyssyy+ohhds:-:/hy//ymmmmmmNmNNmmmdhhdmmmNNNmmmNNmmmNmmddddhhyyhhhdddmddh.                      `sNMN+                                                                                    -dMMMMMMMMMMMMms+-`                                                                                                                            
##              `ss+:/+oydddhysyhdhyyyhysshdddddho+ossyyyyyysos+:-/ydmdyoshdmmmmdhddhyhdmmmh//yhhhddmmmmmmmmdsosdddmmmddmmmmdmmhsssd++/+hmdddmhdmmmd:ommmmmmmo+ydddh+sdmds+hdo+syhs++oohhsoosdd/-/hNdhhmmNNNNNmhssshmmmmmmmNmdhddmNNNmNNmmmmmmmmmNNmmm.                      `sNMN+                                                                                    -dMMMMMMMMMMMhs:.`  `                                                                                                                          
##              `so+:://oyddhssshho::/shddhyhdddy++oyyyhhddddddyooydmmdyoshdmmmmmmmmmmmmmmmh/+y+:-/ydmmdo//yh+ody:odmdy+odmmmmmddmmmmmdmmmmmmmmmmmmmh+hmmNmmmdhyydyo+oyhs+/yh++yhdo//+ydmmmdmmmo.-yms//ymmNNNmNdsssymmmmNmmdyo+oydmmmNNmNmmmmmNNmmmNNm-                      `sNMN+                                                                                    -dMMMMMMMMMMMMNmh+:`                                                                                                                           
##              `ys++/::+yddhssyhy+-.-/yho//+ydh/-://:/+//oyyhhhhhdmmmdhyyhdmmmmmmmmmmmmmmmy/ohyo+ohmmms:-.+y+ymo.::omh+sdmmmmh/+odhosymmmmmmmmmmmmmmmmmmmmmmmmmmmmdddmdhhyydhysshsssoohmNNmmmd/.:hmhosdmmNmmmNdysosdmmmNmho/::+syyyyhdddhddmNNmNmmmdh-                      `sNMN+                                                                                   `-hNNMMMMMMMMMMMMMNmy/.`                                                                                                                        
##              `dhyys++shdhysyydho:-:+yho//+shh/---.-/+/////+oossyhddmdddmmmmmmmmmmmmmmmmmdhdmmmmmmmmd+--.os+hm::o-/my+ymmmmms:/odo/+odmmmmmo/oodmmmmmdhddmNNmmmNmmmmmmmmmNmmmmmmmmmddmmmmmmh+--smh/-/ymmmmmmmdsosydmmmmdy/:-//+++++++o+/osydmmNmmhso.                      `sNMN+                                                                                    .+sssydmMMMMMMMMMMMMNy+``                                                                                                                      
##              `hdddhooshddhhhhddhsoshddhysyhdy/--..-+yhyo/::/+oooosyyyyhhdddmmmdhyhdmmmmmmmmmmmmmmmmmdyyyho+hm+::/yds/hmmmmy/+//o+//odmmmmmhyyymmmmmmo:+/dmmNmmmdydmNNmmmNmmmmNmmNmmmmmmmNds/+ymdo--/hmmmmmmdyoosdmmmmNmh++/oo+/::+/:+/:oyyhmmmmho+/`                      `sNMN+                                                                                         `.-oymNMMMMMMMMMMMs-`                                                                                                                     
##               yddds//+oyyyhhdmddyyhdddmmddmmyo//:-:+ydds+//++o++++o+++ooooyhmmdsoshdddmmmmmmmmmmmmmmmmmmdyoydddddmy++hmmmmh++//+/s:/hmmmmmmmmmmmmmmmdhhhmmmmmmNs:ymNmmmmmNmmmmmmmmmmdhhdmmdddmmdsosdmmNNmmdysosymmmmmNmdyyshho+//+//o+oydhdmmmmy+/:`                      `sNMN+                                                                                            ``:yNNMMMMMMMMMNy:`                                                                                                                    
##               ohdho/::::/:+sydho+/+oshdmmmmmdhhhyooshddhysysoooo+o++/+++oshdmmmsosssosyysshhhhdddmmmmdhdddddmdmmmmhyhmmmdmmmddddhyysdmmmmmmmmmmmmmmmmmmmmmmmmmNo/hmysyyymNmmmmddhdmdyooshyshmmmhyyydmmmmmmmhyyhmmmmmmmmmddmmmhysssyhhhdmmmmmmmds+/:`                      `sNMN+                                                                                               .+dNNMMMMMMMMNs.                                                                                                                    
##              `ohdhs+/:----/oyds/:-.-:ohmddhhdmdhyyyhdmddddddhhhhyyyysssyhhddddho+ooooo++/+oo++osooyhhs+s/-:od/+dmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm+odd+:::/hmmmmms/::odsoydh::+yddhso+ydmmNmNmyooymmhhyhmNmNNNNmmmmmmmmdmmmmmNmmmmh+//.                      `sNMN+                                                                                                `+dNMMMMMMMMMdo`                                                                                                                   
##              `yhdddhso++/+oydho::-.../shs//+sdhso+osyhysyhdmmmmmdmmddddddhsssssoosso+o+//+o+/+o///++o+/sysoymo-smmmmmmmmmmmmmmmddmmmmmmmmmmmmmmmNmmmmmmmNNmNmmd+ommddhhhmmmmmy:-../hsohms-.--:ymyooymmmmmNmo//smmo++sdNNmNNmmmNNmmmmmNmmmmmmmmmdyss.                      `sNMN+                                                                                                 .+NMMMMMMMMMNd.                                                                                                                   
##              `yyyhhddhyyyhddmds/::--:+yhs/:/ohyo+//++s/-:+ydmmmdhdmmmmmmmdyysyhddddhhyo+/++//+s++os+++/ymmmmmy-+dmmmd+smsydyhmmy/ommmy+hmyhmmmmmmmmmmmmmmmmmmNmmmNNmNmNNNmmmms-..-oyoohm+-:/--sdyoohmmmmmNdo//ymd+//smmmmmNmmdddmmmmmmmmmmmmmmmmmdd-                      `sNMN+                                                                                                  :hNMMMMMMMMMN:`                                                                                                                  
##              `ooo++ossyhddmmmmdssooosydmdhyyhdys++++/+-..-+hdds++ydmmmhhhdmmdhyydmmmmdhsssso+oyhhhhysosdmmmmm+-smhhdm+:o:yoo/+dm:+mms:ymms:hmmmmmmmmmmmmmmNmmmmmmmNmNmmmmmmmmdyysydyoohm+----+hdsosdmmmNmmh+//hmy+//ymmmmmmdhs++shdmmmmmmddddmmmmmm-                      `sNMN+                                                                                                  .+mMMMMMMMMMNo-                                                                                                                  
##              `/+/:-://oyhdddhddddysyyhhddddmmmdhsso:-:---:ohdy/:+sdmms::+ydmmh/-+hddmmmdmmdddddmmmmmmmmmmmmdo-odm+/yms::ys-/-/mh-smh:smmmm:ommhymmmmmmmmmmmmmmmNNmmmmmmmmmmmmmmmmmmyoosddhyyyddyo+sdmmmmNmy//+dms//+hmmmmmds+:..:+hmmmmdhysyyhhyyyh-                      `sNMN+                                                                                                  `-dMMMMMMMNMMh:                                                                                                                  
##              `/+/-.-:/+shhy+/shdho/////+osydmmmmddy+++ooosydmds+oydmh/-:sdddmh/-+o//oysshddddmdhdmhdmmmmmmmdyhmmmmdmmmhhmhoo/sy+-sdy:ymdmm:ommysmmmmmmmhsoshmmmNmmmmmmmmmmmmmmmmmmmddddmmmmmmdhsoohmmmmmNds+/omdo//odmmmmmy/:.`.-/yhyhdhysoossssoos-`                     `sNMN+                                                                                                   .hMMMMMMMMMMm/                                                                                                                  
##              `sso+////oyhhs//+sddyo+/://::+shdmmmdhyyhdddmmmmmdhhdmmdo/:os/+ys:-:-....-.://::+:-+y//ymmmmmmhdmmmmmmmmmmmmmmmmmmdhhdd/+dddo:hmdssdmmmmmd//yhdmmmmmhsyyhdmmmmmmdddmmmmmmmmmmmmmmmdddmmmmmmmdyssymdso+smmmmmmy+/--:/+ssooyhsooooooo/+s.`                     `sNMN+                                                                                                   `hNMMMMMMMMMN+                                                                                                                  
##              `ssyyyyssyhdddysyhdmddddhhy/-:/+yddmdyoshdmmmmmmmmmmmmmmdhyhhsyyo::::--:-:::-..-+--/+-.:+dyohy:/dmmmmmmmmmmmddmmmmmmmmmd+hdo+hmdy::mmmmmmd//yhmmmmmms::-:smmmmmy+:/shsosyhdddddmmmmmmmmmmmmmmmddmmmdhhdmNmmmmmhyssyhhyysshhyssso+oo+os.`                     `sNMN+                                                                                                   `hNMMMMMMMMMM+                                                                                                                  
##               +oyhdddhhddmmmmdmmmmmmmmmy/:/:/ohdmmyosydddhyyhdmmmmmmmmmmmmmmmddhhhyssyys+.`.:y:-so-/-:hs+hs.-:+dhsdmmdmmmo/dmmmmmmmmddmmdmmmdsydmmmmmmmdyosdmmmmmdhhyyhmmmmd+--.:+-.:-//:-:/syo+ohhhdmddmmmmmmmdhssydmmmmmmmmmmmmmmddmmddhhyyssssyy.`                     `sNMN+                                                                                                   `hNMMMMMMMMMMo                                                                                                                  
##               ssydddhhddmmdddhhhddmmddds///-:+ydmdyssyddh+--+ydmhyyhdmmmyooshhhdmmmmmmmmy:.-:sy++++s/+ho+ho-y::o/:ydy+ommd:+mdmmmmmy+smmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmms-.-.//-/hy+:.:+///-..://+o++ydmmNmho:-:+ydmmmmmmmmmmmmmmmmmmmmmmdhhhhdm-                      `sNMN+                                                                                                   `yNMMMMMMMMMMo                                                                                                                  
##               ddhddo++sddysssosssyhhyyhhyys++ohmmhssyhdds:..:sddo::/sdmds:-//:-+hmmmmmmmmdyshdmmmmmmdhs-:ys::/yy//ys+-/sdd//mmmmmmdosdmmmmmmmmmmmdhhmmmmmmmmmmNmmmmmmmmmmmmdyoooyo/smms::smy/.``..:-.--/hmmmmy/-..-/++/+oyhyyyhddddddmmmmmmmmmmdmmm-                      `sNMN+                                                                                                   `ymMMMMMMMMMMo`                                                                                                                 
##               mmmmdo/+oyy+://+o/--/+ooshdmddddmmmhyyhdmmho//oymmho++sdmmmhhhys+sysshmmmmmhooymmmmmmmmdyshmmmdmmmhhmmyoymdy:smmmmmds+hmmmmmmmmmmmdo++dmmmmmmmhymmmmmmmmmmmmmmmmmmmmmmmmdyydmd+:---+o-.-/hmmmmmh/..-/:--.-:-:::::://:/+shdmmmmmdhdddm-                      `sNMN+                                                                                                   `ymMMMMMMMMMMo`                                                                                                                 
##               ddmmmhyyydh+:::+o/..-:/oshdmdhdmmmdyoshdmmmmdddmmmmmmdmmmmmmmmmmmmhoohmmmdy/:+yhhdmdmmmmmmmmmmdmmmmmmmmmmms:odmmmmmmh+hmmmmmmmysydmd+sdmmmmNmd+:hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdyhys:.-/hyhhddmds+/+y+:-:o/--..-.......:ohmmmhyo+osso.`                     `sNMN+                                                                                                   `ymMMMMMMMMMMo`                                                                                                                 
##              `hhhhdmdmdmdhso++o/---:/oshdy+:+ydmh+::ohmdysoydmmmmmmmmmmmmmmmmmmms/+hmmmms-:+////so+ohmmmmmdo:yhdmmmmmmmmhdmmmmmmmmh+hmmmmmmmddhmmh+ymmmmmmmd/+ddyyyhdmmmmmmmmmmmmmmmmmmddmmmmmmmds/+shy/---:/oyyyhdsooydo/:.....```..-+hmmdy+:---:-`                      `sNMN+                                                                                                   `ymMMMMMMMMMMo`                                                                                                                 
##              `ssssyhhyhddhhyysyyssoo+syhdy/:/ohmmhyshdmdo::+yhdmmmmdhhdmmmmmmmmh/-/hmmmmy/ss//o::://+hmmmh/-yd-+hdmmmmmmmmmmmmmmmmdyydmmmmmmmmmdyo+ohmmmmmmh/smy:---odmmmmho//sdmmmmmmhsoydmmmmmmmmmmmdyso+++sdmmmmmdddmds+/////:---:/sdmmds/.`.---``                     `sNMN+                                                                                                   `ymMMMMMMMMMMo`                                                                                                                 
##              `oooooosooso//+/oshdddhyyhdmmhyyhdmmmmmmmmmdyyyooydmmmhssydmmmdhhddhhhmmmmmdhdds+/o+/ymdmmmms-+my.-:/mmmmmmmmmmmmmmmddmdmmmmdmdmmmmmmmmmmmmmmmy/ymmhhysymmmmms:-.-smmmmdhs/oydhhhhdmmmhyshmmmmmmmmmmmmmmmmmmmdddddhhys+////+ooo/:-::::``                     `sNMN+                                                                                                   `smMMMMMMMMMMo`                                                                                                                 
##              `soooooo+/+o+++::+oydmddhhhddddmmmmmmmmmmmmmmmdo+ydmmmdssydmmh+::odyoyhddmmmmmmmmdmddmmmmmmmy.+mo-y/:mmmmm++osdmmmmh+oohdmmmmddmmmmmmmmmmmmmNmmmmmmmmmmmmmmmh:...-ydyydmdy++yyo+++syys++oshhhddmdmmmdhyyyhdmmmdddmmmmdhyo/:://++ooosys.                      `sNMN+                                                                                                   `smMMMMMMMMMMo`                                                                                                                 
##              `yyyssssooosshy/-::+hddmhysyoosdmmmmmmmmmmmmmms::ohmmmhsoydmmy/-:so-:o/-:ohhhdddmmmmmmmmmmmmd/-hy///ymmmmdoo+odmmmd/ss+odyydm//dmmmmmmmmmmmmmmmmmmmmmmmmmmmmmyo+/oho-:ydyo/+ysooso+ooo+++oo++osyyyyyysooooshhyssydhysyyhhsoooyhhdddmmm-                      `sNMN+                                                                                                   `sdMMMMMMMMMMo`                                                                                                                 
##              `ddddhhhhyyhddy/::-:ohdmhsos+-/sshdmmmmmmmmmmmy++sdmmdyoshmmNh+::/--odho+oo+/ooshsydmmmmmmmmmdyhmmdmmmmmmmmmmmmmmmd/+hosdysdd::++hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmdhhddyooosssssso+++++/+::/+oo+++++oooooo+oo+oss/://sdmmmdddhyyyhddm-                      `sNMN+                                                                                                   `odMMMMMMMMMMo`                                                                                                                 
##               osyhddmhhhdddhso/-:+hddhsss+-://shmmdyyyyyhdddhdmmmmhysydmmms/:/+-:sdmmdyo/:++sy+oyyhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmyooshmosdh-hy-ymmmmmhs++hmmmmmmmmmmmmmmmmdddmmmmmmmmmmddddddddhhysoosos//+oss+///+oosso+///+so/---+yyo+oyyyssssssyy.`                     `sNMN+                                                                                                   `+hMMMMMMMMMMo`                                                                                                                 
##               --:+hdy+/oyhdddhyssshddysso::///oydmdsooooosyssydmmmmmdmmmmmmhyhd+:+hmmmy+/+++ss+++/shooshhhhdmmmmmdhhdmmmmmmmmmmmmddmdh-+dy/o++dmmmmd/:sdmmmmmmh+/+sdmmmmms::odmmmmmmmmmmmdddmmmmmddhddhysyyyysosoooooooooo+oy+:../so/:-:ossssoo+/:-`                      `sNMN+                                                                                                   `:yMMMMMMMMMMs.                                                                                                                 
##               .`-/sh+----:+osyhhddmmmhyyyoo+:-/sdmdyssoooosoosysyhmmmmmmmmdddmmdyydmmmdhyhhso+oso/oo///s+/+ohmmmmho+hmmmmmmmmmmmdmmmdsydmmdddmmmmmmmdo/ymmmmmh:-yhhmmmmmmd/.+dmhhhdmdddmmdddmddmmmmmmmmmddmdddddhhysssyhyyyhho:-.:o+:../sysssoo/-.`                       `sNMN+                                                                                                    .oMMMMMMMMMMd+`                                                                                                                
##               :-::/s+/:..------:/shmmdddddddysshdmmhyssssssoossooydmmdyosyo/ohdyhmmNmmmmmmmddddhssyy++sy+shhdmmmmmo+dhssydmddmmmmmmmmmmmmmdmmmmmmmmmmmhhmmmmmd/-oydmyyhmmd:.sh/-.-+s+/+ohdhyhhdhyhdmdhhdmmmmmmmmmmdddmmdddddds/--:++/::+sssssoo/-.` `                     `sNMN+                                                                                                     +NMMMMMMMMMMms:.                                                                                                              
##              `yso//+ooo+o+:-..``.:shyooo++yhddmddmmmmddddhyssssoosssho/+ohs:+yo/+hmmddyhmmmmmmmmmmmddhddyhmmmmmmmd+odosy+ssosohhyydddmdmmmmddmmmmmmmmmmmmmmmmmdsoohm/:sdy+.-so.`..--.---:/:--:/:-:+s+//sdmmmmmmdddddmmmmmmmmmdo++oshyoossssoooo+:..``                     `sNMN+                                                                                                     :yNMMMMMMMMMMNmyo:.````````                                                                                                   
##              `hhhysoyhddddyo/:-..:oho:--.-::/oso+yhdmmmmmmmddddhhhsoso//sho:oho:+s+/oo/+yddo/ommddmmmmmmmmdysyyhhs+oyoos+s/+soy+yooyssshdhhood+++ymyommmmmmmmmmmmmmmdddmyo//+o:.--+--/:---...-:-..:/-..-/sdhyyhyoooydmmmmmmmmmdhhddddddddyssssyso+/`                      `sNMN+                                                                                                     `:mNMMMMMMMMMMMNNmmmmdddhhs-`                                                                                                 
##              `sssssyyhdddddhhhys/:/o+:::-----:::-+/+shhhddhyhdddmmmmmmhyss+/+s/:++:oy+::/s+-/hds+oydmmmmmmmdhhyshdmdddhyhy+ooss++oys+s+osos/odss/smy-ommmmmmmmmmmmmmmmmmmdmddmhyssyoos+/-.``.+s:.-so-...-/so++o+:-.:oyddhddmmmmmmdhysshdmdhhhhddhhh.`                     `sNMN+                                                                                                      `+hNMMMMMMMMMMMMMMMMMMMMMh-`                                                                                                 
##              `oooooooossyysyhdddhs++oosso++/+so:-:---:::/+/:++//shhhddmmmmdddhyoss+/o+::+y:-sds//syyhhdddmmmmmmmmmmmmmmmdyooooo+y+syosshosh/smmmmdmm/-dmmmmmddmmmmmmmmmmdddmmmmddmmdddds-....:o+--//::-:-/ys/oy/-..--:+ooosddhyhdds+/:+hmmmmmddhhhh-`                     `sNMN+                                                                                                       `:ymMMMMMMMMMMMMMMMMMMMMh-`                                                                                                 
##              `sooooo+++/+ooossyhdddhddmmmddhhdh+:/:/:...---/o/::+o:/o++shddmmmmmmmmdhhysos:-smy+sy+oyoo+oohdhhhdhhmmmddmmmddddhysshddhhdhsoohmmmmmmm/:dmmmmdo:hy+yhyyhdy/:+hmmhsshmdmdmds+::/ohdysssssss+s+:-:+/-..--.----:+/:/:+hs:--:odmmmmdhysss.`                     `sNMN+                                                                                                         -/dmMMMMMMMMMMMMMMMMMMh-`                                                                                                 
##              `syysssso+//++oo++oshddhhddmmmmmmmdhhhhs:.`---+so::/:-+yo//osssyhdddmmmmmmmdmy:/dhyhho+++o+y+sooyyy+/yhds+dmmmmmmmddmdddmdmmmddmmmmmmdo-smdsodms-o-:s+:-:ymo.:hmy:-/ydmmmmdysyhddmmdmmdmmmdds/-.:oo:--:/+::::+/:---+yo:---odmmmdhysooo.``                    `sNMN+                                                                                                           -/ymNNMMMMMMMMMMMMMMh-`                                                                                                 
##              `/oyyyhhys++++oo++osyhyooossyhhddmmmmddds/-/+:/o/::/-:smmdhs+//+syoshdmmmmmmmmhhmmmmmdhyysshos+oddd+ohdh++ddhyydmdddmdmhsdddmmmmmmmmdo/ymdds+hmh/-/yo.-.-sm+.+mh-.+hdy+oshd/-:smmmmmmmmmmmmdyo+ohddhyyyhdyysshy++//sy+---:smmmmdysooos-``                    `sNMN+                                                                                                            `..+oyhhdddmmmmmmmmy-`                                                                                                 
##               ::/+osyhyyssyyyssssyyso++ooooossyyys++sysyhdhyhyyyh+:+hmmds+/++ssooooyddhdmmmmmmmmmmmmmmmmmddhyshdoohddo+msohooy+ssdds/sdd+smmmmmmmmddmmmmmmmmmhydds::-:so-.+do.-hmy/-../dy-./ddyyydmmmmmmmdddmmddmmmmmmmddmmdhhhhho:-.:odmmmmdysoooy-                      `sNMN+                                                                                                               ` ``..-----------`                                                                                                  
##               -.`..--::////////::::-------------:-....-://///////:.-:///:--:-::-:--::--::///////////////////////::-:-.-/--/:.:-:.::.-///-.////////////////////////::---.``.:-`.:/-````.::.`.::..-:////////:://::////////////////::-.`.://////::::-:`                      `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `sNMN+                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                           `/hhy/                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                             ````                                                                                                                                                                                                                                   
##                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
